export { collectProjectProfile } from './collect';
export type { DetectorContext } from './context';
export type {
  ProjectProfile,
  ProjectConvention,
  PhpStackInfo,
  JavascriptStackInfo,
} from './types';
export { PROJECT_DETECTORS, type ProjectDetector } from './registry';
export {
  CONVENTION_DETECTORS,
  type ConventionDetector,
} from './conventions/registry';
export {
  scanProdRisks,
  BUILTIN_PROD_RISK_RULES,
  loadPackProdRiskRules,
  PROD_RISK_CATEGORIES,
  isKnownProdRiskCategory,
  type ProdRiskCategory,
  type ProdRiskCategorySummary,
  type ProdRiskFinding,
  type ProdRiskLanguage,
  type ProdRiskRequiredSignal,
  type ProdRiskRule,
  type ProdRiskScanProgress,
  type ProdRiskScanResult,
  type ProdRiskScannerOptions,
  type ProdRiskSeverity,
} from './prod-risks';
export {
  RagStore,
  ragStoreDir,
  ragStorePath,
  ragJsonMirrorPath,
  indexWorkspace,
  retrieveFromWorkspace,
  retrieve,
  tokenize,
  chunkFile,
  chunkPhp,
  chunkMarkdown,
  ingestMarkdownMemory,
  PRIORITY_MEMORY_BASENAMES,
  sha256,
  type EmbeddingPort,
  type ExplanationCacheEntry,
  type ExplanationMode,
  type IntelligenceProfile,
  type IndexProgress,
  type IndexProgressCallback,
  type RagChunk,
  type RagHit,
  type RagDependencyEdge,
  type RagSymbolRecord,
  type RetrieveOptions,
} from './rag';

export type {
  SourceType,
  ExclusionReason,
  ExclusionRecord,
  WorkspaceDescriptor,
  FileFingerprint,
  ParseStatus,
  FileRecord,
  SymbolLocation,
  SymbolParameter,
  SymbolRecord,
  EdgeResolutionMethod,
  EdgeConfidence,
  DependencyEdgeKind,
  DependencyEdge,
  DocumentChunk,
  InstructionDocument,
  InstructionRule,
  SourceReference,
  ContextClaim,
  ContextResult,
  ContextPack,
  RelationshipPathNode,
  RelationshipPathStep,
  RelationshipPath,
  TraverseDirection,
  TraverseWeightProfile,
  TraverseStopWhen,
  TraverseBudget,
  ChangeImpactTarget,
  ChangeImpactNode,
  ChangeImpactReport,
  ApplicableInstructionRef,
  IndexStatus,
  IndexPhase,
  SourceAuthored,
  SourceExtraction,
  ConfidenceLevel,
  ComponentCertainty,
  SourceFreshness,
  ConfidenceComponents,
  ClaimConfidence,
  PrivacyClassification,
  PrivacyRuleSource,
  PrivacyRule,
  PrivacyDecision,
  AdapterCapabilityLevel,
  LanguageAdapterCapabilities,
  LanguageProjectHint,
  AdapterDiagnostic,
  LanguageAdapter,
  IndexStore,
  RetrieveQueryOptions,
  RepositoryRetriever,
  ModelProvider,
} from './contracts';
export {
  noopModelProvider,
  DETERMINISTIC_EDGE_RESOLUTION,
  isDeterministicEdgeResolution,
  serializeWorkspaceDescriptor,
  parseWorkspaceDescriptor,
  serializeFileFingerprint,
  parseFileFingerprint,
  serializeFileRecord,
  parseFileRecord,
  serializeSymbolLocation,
  parseSymbolLocation,
  serializeSymbolRecord,
  parseSymbolRecord,
  serializeDependencyEdge,
  parseDependencyEdge,
  serializeDocumentChunk,
  parseDocumentChunk,
  serializeSourceReference,
  parseSourceReference,
  serializeContextClaim,
  parseContextClaim,
  serializeContextResult,
  parseContextResult,
  serializeInstructionRule,
  parseInstructionRule,
  serializeInstructionDocument,
  parseInstructionDocument,
  serializeContextPack,
  parseContextPack,
  serializeIndexStatus,
  parseIndexStatus,
} from './contracts';

export {
  createRepositoryIndex,
  type CreateRepositoryIndexOptions,
  type RepositoryIndex,
  type IndexOptions,
  type ContextPackOptions,
} from './api/repository-index';

export {
  createRepositorySearchEngine,
  searchRepositoryContext,
  repositoryContextToClaims,
  hybridSearchRepositoryContext,
  hitsToClaims,
  evaluateRetrievalTasks,
  precisionAtK,
  recallAtK,
  meanReciprocalRank,
  LexicalRepositoryRetriever,
  DEFAULT_RETRIEVAL_BUDGETS,
  type RepositorySearchEngine,
  type CreateRepositorySearchEngineOptions,
  type RepositoryContextResult,
  type RetrievalHit,
  type RetrievalBudgets,
  type RetrievalDebugInfo,
  type SearchRepositoryContextOptions,
  type ScoreBreakdown,
  type EvalTask,
  type EvalTaskResult,
  type EvalSummary,
} from './retrieve';

export {
  createRepositoryFileIndexer,
  type CreateRepositoryFileIndexerOptions,
  type RepositoryFileIndexer,
  type FileChange,
  scanWorkspace,
  evaluatePathForIndex,
  isTempPath,
  isSupportedIndexPath,
  languageForPath,
} from './indexer';

export {
  defaultLanguageAdapters,
  resolveLanguageAdapter,
  detectWorkspaceLanguages,
  collectAdapterEdges,
  TypeScriptLanguageAdapter,
  JavaScriptLanguageAdapter,
  MarkdownLanguageAdapter,
  PhpLanguageAdapter,
  GenericLanguageAdapter,
} from './adapters';

export { createIgnoreMatcher, resolveInsideWorkspace, NestedIgnoreResolver } from './ignore';
export { SqlJsIndexStore } from './store/sqljs-index-store';
export { discoverInstructionDocuments } from './memory/discover-instructions';
export { STORE_SCHEMA_VERSION } from './rag/store';

export {
  PRIVACY_STRENGTH,
  PRIVACY_SOURCE_RANK,
  allowsRetrieval,
  allowsModelEvidence,
  allowsContentStorage,
  allowsSymbolIndex,
  isIncluded,
  decisionFromClassification,
  compareRulePriority,
  wouldWeaken,
  blocksModelEvidence,
  DEFAULT_PRIVACY_PATTERNS,
  globalPrivacyConfigPath,
  workspacePrivacyConfigPath,
  workspacePrivacyOverridesPath,
  parsePrivacyRulesFile,
  loadPrivacyRulesFile,
  loadPrivacyOverrides,
  savePrivacyOverride,
  defaultPrivacyRules,
  vscodeExtraExclusionRules,
  loadAllPrivacyRules,
  evaluatePathPrivacy,
  createPrivacyRuleEngine,
  previewIndexRules,
  classificationAllowsModelEvidence,
  filterPathsForModelEvidence,
  filterItemsForModelEvidence,
  loadPrivacyDecisionsForPaths,
  redactChunkTextForPrivacy,
  assertPathAllowedForModelEvidence,
  type PrivacyRulesFile,
  type PrivacyOverridesFile,
  type LoadAllPrivacyRulesOptions,
  type EvaluatePrivacyOptions,
  type PrivacyRuleEngine,
  type CreatePrivacyEngineOptions,
  type IndexRulePreviewRow,
  type PreviewIndexRulesResult,
  type PreviewIndexRulesOptions,
} from './privacy';

export {
  // Engineering memory (persistent local structure)
  initialiseMergeCoreMemory,
  loadMergeCoreConfig,
  parseMemoryDocument,
  serialiseMemoryDocument,
  loadProvenanceGraph,
  saveProvenanceGraph,
  validateProvenanceDocument,
  validateProvenanceGraph,
  isSelfReinforcingClaim,
  writeGeneratedMemoryDocument,
  mergePreservingHumanSections,
  updateMemoryStatusOnDisk,
  deleteMemoryDocument,
  refreshStaleMemory,
  listGeneratedMemoryFiles,
  detectStaleDocument,
  scanGeneratedMemoryForStale,
  filterDocumentsForRetrieval,
  memoryStatusInfluencesAnswers,
  precedenceForMemoryStatus,
  fingerprintFile,
  MEMORY_AUTHORITY,
  MEMORY_STATUSES,
  MEMORY_SCHEMA_VERSION,
  DEFAULT_MERGECORE_CONFIG,
  MEMORY_DIR,
  GENERATED_DIR,
  GENERATED_MEMORY_DIR,
  RAG_DIR,
  CONFIG_PATH,
  PROVENANCE_PATH,
  SHAREABLE_MEMORY_FILES,
  type MemoryStatus,
  type MemoryFrontmatter,
  type ProvenanceGraph,
  type MergeCoreConfig,
  type StaleCheckResult,
  type InitMemoryResult,
} from './memory';

export {
  createInstructionResolver,
  discoverContextDocuments,
  classifyContextPath,
  chunkMarkdownByHeadings,
  extractInstructionTexts,
  parseFrontmatter,
  pathMatchesGlob,
  PRECEDENCE,
  type InstructionResolver,
  type ContextDocument,
  type ContextDocumentType,
  type ApplicableInstruction,
  type InstructionConflict,
  type InstructionPrecedenceExplanation,
  type MarkdownSection,
  type InstructionResolverOptions,
} from './instructions';

export {
  // Task context packs
  assembleTaskContextPack,
  writeTaskContextPack,
  budgetsForDepth,
  parseTaskContextDepth,
  packHasRequiredSections,
  parseTaskContextFrontmatter,
  detectTaskRiskIndicators,
  REQUIRED_TASK_CONTEXT_SECTIONS,
  TASK_CONTEXT_SCHEMA_VERSION,
  type TaskContextPack,
  type TaskContextInput,
  type TaskContextDepth,
  type TaskContextMeta,
  type TaskRiskIndicator,
} from './context/index';

export {
  createCodeGraphQuery,
  createTsJsCodeGraphService,
  TsProgramHost,
  discoverTsConfigs,
  extractFileWithCompiler,
  symbolAtPosition,
  isLikelyTestPath,
  detectTestCoverageEdges,
  GraphReconcileScheduler,
  buildSymbolId,
  isTsJsPath,
  languageForTsJs,
  normaliseRel,
  traverseRelationshipPaths,
  analyseChangeImpact,
  DEFAULT_TRAVERSE_BUDGET,
  mergeTraverseBudget,
  scoreRelationshipPath,
  formatRelationshipPathLabel,
  confidenceRank,
  type CodeGraphQuery,
  type FindSymbolOptions,
  type RelatedTestResult,
  type SymbolPosition,
  type TraverseNode,
  type TraverseOptions,
  type FileGraphExtract,
  type TsJsCodeGraphService,
  type TraverseStart,
  type TraverseRelationshipPathsOptions,
  type AnalyseChangeImpactOptions,
} from './graph';

export {
  createSourceReference,
  createAttributedClaim,
  computeClaimConfidence,
  confidenceFromRetrieval,
  assertClaimAttributed,
  assignEvidenceIds,
  evidenceMapById,
  validateModelClaimBundle,
  parseModelClaimsJson,
  inspectSourceReference,
  sourceRangeForReveal,
  formatClaimAttributionLabel,
  normaliseSourcePath,
  GENERAL_CONSIDERATION_LABEL,
  AttributionError,
  type SourceReferenceInput,
  type ModelClaimInput,
  type ModelClaimsBundle,
  type ModelClaimValidationResult,
  type SourceLinkInspection,
  type SourceLinkStatus,
  type WorkspaceRootRef,
} from './attribution/index';
