export type {
  SourceType,
  ExclusionReason,
  ExclusionRecord,
  WorkspaceDescriptor,
  FileFingerprint,
  ParseStatus,
  FileRecord,
  SymbolLocation,
  SymbolParameter,
  SymbolRecord,
  EdgeResolutionMethod,
  EdgeConfidence,
  DependencyEdgeKind,
  DependencyEdge,
  DocumentChunk,
  InstructionDocument,
  InstructionRule,
  SourceReference,
  ContextClaim,
  ContextResult,
  ContextPack,
  IndexStatus,
  IndexPhase,
  SourceAuthored,
  SourceExtraction,
  ConfidenceLevel,
  ComponentCertainty,
  SourceFreshness,
  ConfidenceComponents,
  ClaimConfidence,
} from './types';

export {
  DETERMINISTIC_EDGE_RESOLUTION,
  isDeterministicEdgeResolution,
} from './types';

export type {
  AdapterCapabilityLevel,
  LanguageAdapterCapabilities,
  LanguageProjectHint,
  AdapterDiagnostic,
  LanguageAdapter,
  IndexStore,
  RetrieveQueryOptions,
  RepositoryRetriever,
  ModelProvider,
} from './ports';

export { noopModelProvider } from './ports';

export {
  serializeWorkspaceDescriptor,
  parseWorkspaceDescriptor,
  serializeFileFingerprint,
  parseFileFingerprint,
  serializeFileRecord,
  parseFileRecord,
  serializeSymbolLocation,
  parseSymbolLocation,
  serializeSymbolRecord,
  parseSymbolRecord,
  serializeDependencyEdge,
  parseDependencyEdge,
  serializeDocumentChunk,
  parseDocumentChunk,
  serializeSourceReference,
  parseSourceReference,
  serializeContextClaim,
  parseContextClaim,
  serializeContextResult,
  parseContextResult,
  serializeInstructionRule,
  parseInstructionRule,
  serializeInstructionDocument,
  parseInstructionDocument,
  serializeContextPack,
  parseContextPack,
  serializeIndexStatus,
  parseIndexStatus,
} from './codec';
