import type { ReviewResult } from '../../domain/review-types';
import { buildScoreInsight } from './score-insight';

function formatScoreForExport(score: number): string {
  if (score % 1 === 0) {
    return String(Math.round(score));
  }
  return String(Number(score.toFixed(2)));
}

export function formatReviewAsMarkdown(result: ReviewResult): string {
  const lines: string[] = [];
  lines.push('# MergeCore review');
  lines.push('');
  lines.push(`**Score:** ${formatScoreForExport(result.score)}/10`);
  lines.push('');
  const insight = buildScoreInsight(result);
  lines.push('## Score detail');
  lines.push('');
  lines.push(insight.whyText);
  lines.push('');
  for (const d of insight.dimensions) {
    lines.push(
      `- **${d.label}:** ${d.level} (${formatScoreForExport(d.subScore)}/10)`
    );
  }
  lines.push('');
  lines.push('### What went well');
  lines.push('');
  for (const t of insight.strengths) {
    lines.push(`- ${t}`);
  }
  lines.push('');
  lines.push('### To reach 10');
  lines.push('');
  insight.pathToTen.forEach((t, i) => {
    lines.push(`${i + 1}. ${t}`);
  });
  if (insight.residualNote) {
    lines.push('');
    lines.push(`_${insight.residualNote}_`);
  }
  lines.push('');
  if (result.summary) {
    lines.push(result.summary);
    lines.push('');
  }
  lines.push('## Findings');
  lines.push('');
  if (result.findings.length === 0) {
    lines.push('_No findings._');
    lines.push('');
  } else {
    for (const f of result.findings) {
      lines.push(`### ${f.severity.toUpperCase()}: ${f.message}`);
      lines.push('');
      if (f.category) {
        lines.push(`- **Category:** ${f.category}`);
      }
      if (f.code) {
        lines.push(`- **Code:** ${f.code}`);
      }
      if (f.whyItMatters) {
        lines.push('');
        lines.push('**Why it matters**');
        lines.push('');
        lines.push(f.whyItMatters);
      }
      if (f.fixHint) {
        lines.push('');
        lines.push('**Suggested fix**');
        lines.push('');
        lines.push(f.fixHint);
      }
      lines.push('');
    }
  }
  if (result.improvedCode) {
    lines.push('## Suggested rewrite');
    lines.push('');
    if (result.rewriteSummary) {
      lines.push(result.rewriteSummary);
      lines.push('');
    }
    if (result.rewriteAmends && result.rewriteAmends.length > 0) {
      lines.push('### Amends in this file');
      lines.push('');
      for (const a of result.rewriteAmends) {
        lines.push(
          `- **Lines ${a.startLine}–${a.endLine}**${a.label ? ` (${a.label})` : ''}: ${a.rationale}`
        );
      }
      lines.push('');
    }
    if (result.crossFileImpacts && result.crossFileImpacts.length > 0) {
      lines.push('### Other files to update (manual)');
      lines.push('');
      for (const c of result.crossFileImpacts) {
        lines.push(`- **${c.path}**`);
        lines.push(`  - ${c.rationale}`);
        if (c.suggestedChange) {
          lines.push('');
          lines.push('```');
          lines.push(String(c.suggestedChange));
          lines.push('```');
        }
      }
      lines.push('');
    }
    lines.push('```php');
    lines.push(result.improvedCode);
    lines.push('```');
    lines.push('');
  }
  if (result.patch) {
    lines.push('## Patch');
    lines.push('');
    lines.push('```diff');
    lines.push(result.patch);
    lines.push('```');
    lines.push('');
  }
  lines.push('---');
  lines.push('_Generated by MergeCore_');
  return lines.join('\n');
}
